Base project
reclamei/ms-company pull request #2
Opened 2023-08-09 01:31 UTC by liviaaurich

2023-08-11 13:43 UTC, gudeck requested changes

2023-08-11 13:43 UTC, gudeck commented on company.iml
esse arquivo n era pra estar aqui, ele tá no .ignore
![image](https://github.com/reclamei/ms-company/assets/49893876/9e9600d2-5ad5-4fcd-b3de-acc38a30074b)

2023-08-11 13:43 UTC, gudeck commented on src/local/company/docker-compose.yml
> +        restart: always
remover esse restart always pra diminuir o processamento em segundo plano (mesmo sem o projeto estar aberto)

2023-08-11 13:43 UTC, gudeck commented on .env
esse arquivo deveria estar dentro da pasta /local, na raiz do projeto

2023-08-11 13:43 UTC, gudeck commented on src/local/.env
a pasta /local deveria estar na raiz do projeto, fora do src

2023-08-11 13:43 UTC, gudeck commented on src/main/java/br/com/reclamei/company/dataprovider/database/config/DatabaseConfiguration.java
> +        log.debug("Configuring Liquibase");
pelo log estar no final do método, acho que seria uma boa botar a mensagem falando q deu tudo certo, como: "Configuring Liquibase ended successfully"." ou "Liquibase configuration ended." ou afins

2023-08-11 20:52 UTC, liviaaurich commented on company.iml
fiquei assim também

2023-08-14 23:58 UTC, gudeck approved these changes

2023-08-15 01:21 UTC, merged